"""
TradingView strategy.exit() Python Implementation

This module provides a Python implementation of TradingView's strategy.exit()
function with exact algorithmic matching for consistent backtesting results.

Reference: https://www.tradingview.com/pine-script-reference/v5/#fun_strategy.exit

Key behaviors implemented:
1. Stop-loss orders (via `stop` price or `loss` ticks)
2. Take-profit/limit orders (via `limit` price or `profit` ticks)
3. Trailing stop orders (via `trail_price`/`trail_points` and `trail_offset`)
4. Partial exits (via `qty` or `qty_percent`)
5. OCA (One-Cancels-All) order groups
6. Intrabar fill simulation matching TradingView's broker emulator

Author: TV2PY Project
License: MIT
"""

from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Optional, List, Callable, Any
import math


class PositionSide(Enum):
    """Position direction."""
    LONG = "long"
    SHORT = "short"


class ExitType(Enum):
    """Type of exit that was triggered."""
    PROFIT = "profit"        # Triggered by profit/limit
    LOSS = "loss"            # Triggered by stop/loss
    TRAILING = "trailing"    # Triggered by trailing stop
    MANUAL = "manual"        # Manual exit


class OrderStatus(Enum):
    """Order status."""
    PENDING = "pending"      # Order placed but not yet active
    ACTIVE = "active"        # Order is active and monitoring
    FILLED = "filled"        # Order has been filled
    CANCELLED = "cancelled"  # Order has been cancelled


@dataclass
class BarData:
    """
    OHLCV bar data structure.

    Attributes:
        open: Opening price
        high: Highest price
        low: Lowest price
        close: Closing price
        volume: Trading volume
        timestamp: Bar timestamp (optional)
    """
    open: float
    high: float
    low: float
    close: float
    volume: float = 0.0
    timestamp: Any = None

    def get_intrabar_path(self) -> List[float]:
        """
        Get the assumed intrabar price path.

        TradingView's broker emulator uses this logic:
        - If high is closer to open than low: open → high → low → close
        - If low is closer to open than high: open → low → high → close

        Returns:
            List of prices in order of assumed movement
        """
        dist_to_high = abs(self.high - self.open)
        dist_to_low = abs(self.low - self.open)

        if dist_to_high <= dist_to_low:
            # High is closer to open: O → H → L → C
            return [self.open, self.high, self.low, self.close]
        else:
            # Low is closer to open: O → L → H → C
            return [self.open, self.low, self.high, self.close]


@dataclass
class ExitOrder:
    """
    Represents an exit order generated by strategy.exit().

    This class encapsulates all the state and logic for an exit order,
    including trailing stop management.
    """
    # Order identification
    id: str
    from_entry: Optional[str] = None

    # Position info
    position_side: PositionSide = PositionSide.LONG
    entry_price: float = 0.0
    position_qty: float = 0.0

    # Quantity parameters
    qty: Optional[float] = None
    qty_percent: Optional[float] = None

    # Profit target parameters (absolute price takes precedence if closer)
    profit: Optional[float] = None      # Profit target in ticks
    limit: Optional[float] = None       # Profit target price (absolute)

    # Stop loss parameters (absolute price takes precedence if closer)
    loss: Optional[float] = None        # Stop loss in ticks
    stop: Optional[float] = None        # Stop loss price (absolute)

    # Trailing stop parameters
    trail_price: Optional[float] = None     # Activation price level
    trail_points: Optional[float] = None    # Activation in ticks profit
    trail_offset: Optional[float] = None    # Trail distance in ticks

    # OCA (One-Cancels-All) group
    oca_name: Optional[str] = None

    # Comments for different exit types
    comment: Optional[str] = None
    comment_profit: Optional[str] = None
    comment_loss: Optional[str] = None
    comment_trailing: Optional[str] = None

    # Alert messages for different exit types
    alert_message: Optional[str] = None
    alert_profit: Optional[str] = None
    alert_loss: Optional[str] = None
    alert_trailing: Optional[str] = None

    # Tick size for the instrument
    tick_size: float = 0.01

    # Internal state
    status: OrderStatus = OrderStatus.PENDING
    trailing_activated: bool = False
    trailing_stop_price: Optional[float] = None
    best_price: Optional[float] = None  # Best price since trail activation
    fill_price: Optional[float] = None
    exit_type: Optional[ExitType] = None

    def __post_init__(self):
        """Validate parameters after initialization."""
        # Validate trailing stop parameters
        if self.trail_offset is not None:
            if self.trail_price is None and self.trail_points is None:
                raise ValueError(
                    "trail_offset requires either trail_price or trail_points"
                )

        if (self.trail_price is not None or self.trail_points is not None):
            if self.trail_offset is None:
                raise ValueError(
                    "trail_price/trail_points requires trail_offset"
                )

        # Validate quantity parameters
        if self.qty is not None and self.qty_percent is not None:
            raise ValueError("Cannot specify both qty and qty_percent")

        if self.qty_percent is not None:
            if self.qty_percent <= 0 or self.qty_percent > 100:
                raise ValueError("qty_percent must be between 0 and 100")

    def get_exit_qty(self) -> float:
        """
        Calculate the quantity to exit.

        Returns:
            The quantity to exit based on qty, qty_percent, or full position
        """
        if self.qty is not None:
            return min(self.qty, self.position_qty)
        elif self.qty_percent is not None:
            return self.position_qty * (self.qty_percent / 100.0)
        else:
            return self.position_qty

    def _ticks_to_price(self, ticks: float) -> float:
        """Convert ticks to price difference."""
        return ticks * self.tick_size

    def get_limit_price(self) -> Optional[float]:
        """
        Calculate the effective limit (take profit) price.

        Pine Script v6+ behavior: evaluates both limit and profit parameters
        and uses the level expected to trigger first.

        Returns:
            The effective limit price, or None if no limit is set
        """
        limit_from_price = self.limit
        limit_from_ticks = None

        if self.profit is not None:
            profit_offset = self._ticks_to_price(self.profit)
            if self.position_side == PositionSide.LONG:
                limit_from_ticks = self.entry_price + profit_offset
            else:
                limit_from_ticks = self.entry_price - profit_offset

        # If both are specified, use the one expected to trigger first
        if limit_from_price is not None and limit_from_ticks is not None:
            if self.position_side == PositionSide.LONG:
                # For longs, lower limit triggers first
                return min(limit_from_price, limit_from_ticks)
            else:
                # For shorts, higher limit triggers first
                return max(limit_from_price, limit_from_ticks)

        return limit_from_price if limit_from_price is not None else limit_from_ticks

    def get_stop_price(self) -> Optional[float]:
        """
        Calculate the effective stop loss price.

        Pine Script v6+ behavior: evaluates both stop and loss parameters
        and uses the level expected to trigger first.

        Returns:
            The effective stop price, or None if no stop is set
        """
        stop_from_price = self.stop
        stop_from_ticks = None

        if self.loss is not None:
            loss_offset = self._ticks_to_price(self.loss)
            if self.position_side == PositionSide.LONG:
                stop_from_ticks = self.entry_price - loss_offset
            else:
                stop_from_ticks = self.entry_price + loss_offset

        # If both are specified, use the one expected to trigger first
        if stop_from_price is not None and stop_from_ticks is not None:
            if self.position_side == PositionSide.LONG:
                # For longs, higher stop triggers first
                return max(stop_from_price, stop_from_ticks)
            else:
                # For shorts, lower stop triggers first
                return min(stop_from_price, stop_from_ticks)

        return stop_from_price if stop_from_price is not None else stop_from_ticks

    def get_trail_activation_price(self) -> Optional[float]:
        """
        Calculate the trailing stop activation price.

        Can be activated by:
        - trail_price: absolute price level
        - trail_points: ticks of profit from entry

        If both are specified, whichever triggers first activates the trail.

        Returns:
            The activation price, or None if no trailing stop
        """
        if self.trail_offset is None:
            return None

        activation_from_price = self.trail_price
        activation_from_ticks = None

        if self.trail_points is not None:
            points_offset = self._ticks_to_price(self.trail_points)
            if self.position_side == PositionSide.LONG:
                activation_from_ticks = self.entry_price + points_offset
            else:
                activation_from_ticks = self.entry_price - points_offset

        # If both specified, use whichever triggers first
        if activation_from_price is not None and activation_from_ticks is not None:
            if self.position_side == PositionSide.LONG:
                # For longs, lower activation price triggers first
                return min(activation_from_price, activation_from_ticks)
            else:
                # For shorts, higher activation price triggers first
                return max(activation_from_price, activation_from_ticks)

        return (activation_from_price if activation_from_price is not None
                else activation_from_ticks)

    def check_trail_activation(self, price: float) -> bool:
        """
        Check if trailing stop should be activated at given price.

        Args:
            price: Current price to check

        Returns:
            True if trailing stop was just activated
        """
        if self.trailing_activated:
            return False

        activation_price = self.get_trail_activation_price()
        if activation_price is None:
            return False

        # Check if activation condition is met
        if self.position_side == PositionSide.LONG:
            # For longs, activate when price >= activation price
            if price >= activation_price:
                self._activate_trailing(price)
                return True
        else:
            # For shorts, activate when price <= activation price
            if price <= activation_price:
                self._activate_trailing(price)
                return True

        return False

    def _activate_trailing(self, activation_price: float) -> None:
        """
        Activate the trailing stop at given price.

        Args:
            activation_price: The price at which trailing stop activates
        """
        self.trailing_activated = True
        self.best_price = activation_price

        # Calculate initial trailing stop price
        trail_offset_price = self._ticks_to_price(self.trail_offset)

        if self.position_side == PositionSide.LONG:
            # For longs, stop is trail_offset ticks BELOW best price
            self.trailing_stop_price = self.best_price - trail_offset_price
        else:
            # For shorts, stop is trail_offset ticks ABOVE best price
            self.trailing_stop_price = self.best_price + trail_offset_price

    def update_trailing_stop(self, price: float) -> None:
        """
        Update trailing stop based on new price.

        The trailing stop follows the price, adjusting when price moves
        favorably. It never moves backwards.

        Args:
            price: Current price
        """
        if not self.trailing_activated:
            # Try to activate
            self.check_trail_activation(price)
            return

        trail_offset_price = self._ticks_to_price(self.trail_offset)

        if self.position_side == PositionSide.LONG:
            # For longs, update if price makes new high
            if price > self.best_price:
                self.best_price = price
                new_stop = self.best_price - trail_offset_price
                # Trailing stop only moves up, never down
                if new_stop > self.trailing_stop_price:
                    self.trailing_stop_price = new_stop
        else:
            # For shorts, update if price makes new low
            if price < self.best_price:
                self.best_price = price
                new_stop = self.best_price + trail_offset_price
                # Trailing stop only moves down, never up
                if new_stop < self.trailing_stop_price:
                    self.trailing_stop_price = new_stop

    def check_trailing_stop_hit(self, price: float) -> bool:
        """
        Check if trailing stop has been hit.

        Args:
            price: Current price

        Returns:
            True if trailing stop was hit
        """
        if not self.trailing_activated or self.trailing_stop_price is None:
            return False

        if self.position_side == PositionSide.LONG:
            return price <= self.trailing_stop_price
        else:
            return price >= self.trailing_stop_price

    def get_comment(self) -> Optional[str]:
        """Get the appropriate comment based on exit type."""
        if self.exit_type == ExitType.PROFIT and self.comment_profit:
            return self.comment_profit
        elif self.exit_type == ExitType.LOSS and self.comment_loss:
            return self.comment_loss
        elif self.exit_type == ExitType.TRAILING and self.comment_trailing:
            return self.comment_trailing
        return self.comment

    def get_alert_message(self) -> Optional[str]:
        """Get the appropriate alert message based on exit type."""
        if self.exit_type == ExitType.PROFIT and self.alert_profit:
            return self.alert_profit
        elif self.exit_type == ExitType.LOSS and self.alert_loss:
            return self.alert_loss
        elif self.exit_type == ExitType.TRAILING and self.alert_trailing:
            return self.alert_trailing
        return self.alert_message


@dataclass
class ExitResult:
    """Result of an exit order check/execution."""
    filled: bool = False
    exit_type: Optional[ExitType] = None
    fill_price: Optional[float] = None
    qty: float = 0.0
    comment: Optional[str] = None
    alert_message: Optional[str] = None
    order_id: str = ""
    from_entry: Optional[str] = None


class StrategyExit:
    """
    TradingView strategy.exit() implementation.

    This class manages exit orders and simulates the TradingView broker
    emulator's behavior for consistent backtesting results.

    Usage:
        strategy_exit = StrategyExit(tick_size=0.01)

        # Create an exit order
        order = strategy_exit.exit(
            id="exit1",
            from_entry="entry1",
            position_side=PositionSide.LONG,
            entry_price=100.0,
            position_qty=10.0,
            profit=50,      # 50 ticks profit target
            loss=25,        # 25 ticks stop loss
            trail_points=30,  # Activate trail at 30 ticks profit
            trail_offset=20,  # Trail 20 ticks behind best price
        )

        # Process each bar
        bar = BarData(open=101.0, high=102.0, low=100.5, close=101.5)
        result = strategy_exit.process_bar(bar)

    Attributes:
        tick_size: Minimum price increment for the instrument
        orders: Dictionary of active exit orders
        oca_groups: Dictionary of OCA (One-Cancels-All) groups
    """

    def __init__(
        self,
        tick_size: float = 0.01,
        calc_on_order_fills: bool = False,
        process_orders_on_close: bool = False,
    ):
        """
        Initialize the StrategyExit manager.

        Args:
            tick_size: Minimum price increment (syminfo.mintick)
            calc_on_order_fills: If True, process on each fill (like TradingView)
            process_orders_on_close: If True, process orders at bar close
        """
        self.tick_size = tick_size
        self.calc_on_order_fills = calc_on_order_fills
        self.process_orders_on_close = process_orders_on_close
        self.orders: dict[str, ExitOrder] = {}
        self.oca_groups: dict[str, List[str]] = {}  # oca_name -> list of order ids

    def exit(
        self,
        id: str,
        from_entry: Optional[str] = None,
        position_side: PositionSide = PositionSide.LONG,
        entry_price: float = 0.0,
        position_qty: float = 0.0,
        qty: Optional[float] = None,
        qty_percent: Optional[float] = None,
        profit: Optional[float] = None,
        limit: Optional[float] = None,
        loss: Optional[float] = None,
        stop: Optional[float] = None,
        trail_price: Optional[float] = None,
        trail_points: Optional[float] = None,
        trail_offset: Optional[float] = None,
        oca_name: Optional[str] = None,
        comment: Optional[str] = None,
        comment_profit: Optional[str] = None,
        comment_loss: Optional[str] = None,
        comment_trailing: Optional[str] = None,
        when: bool = True,
        alert_message: Optional[str] = None,
        alert_profit: Optional[str] = None,
        alert_loss: Optional[str] = None,
        alert_trailing: Optional[str] = None,
    ) -> Optional[ExitOrder]:
        """
        Create an exit order (mirrors TradingView's strategy.exit).

        This command generates exit orders with the following order types:
        - Stop-loss order (via `stop` or `loss`)
        - Take-profit/limit order (via `limit` or `profit`)
        - Trailing stop order (via `trail_price`/`trail_points` and `trail_offset`)

        Args:
            id: A required parameter. Order identifier.
            from_entry: An optional parameter. Identifier of entry order.
            position_side: Long or short position.
            entry_price: Entry price of the position.
            position_qty: Total position quantity.
            qty: Number of contracts/shares/lots/units to exit.
            qty_percent: Percentage of position to exit (0-100).
            profit: Profit target in ticks from entry price.
            limit: Profit target as absolute price.
            loss: Stop loss in ticks from entry price.
            stop: Stop loss as absolute price.
            trail_price: Trailing stop activation price level.
            trail_points: Trailing stop activation in ticks of profit.
            trail_offset: Trailing stop distance in ticks (required with trail_price/trail_points).
            oca_name: OCA group name. Orders in same group cancel each other.
            comment: Order comment.
            comment_profit: Comment if exit triggered by profit/limit.
            comment_loss: Comment if exit triggered by stop/loss.
            comment_trailing: Comment if exit triggered by trailing stop.
            when: Condition to place order. If False, order is not placed.
            alert_message: Alert message placeholder text.
            alert_profit: Alert if exit triggered by profit/limit.
            alert_loss: Alert if exit triggered by stop/loss.
            alert_trailing: Alert if exit triggered by trailing stop.

        Returns:
            The created ExitOrder, or None if when=False
        """
        if not when:
            return None

        # Create the exit order
        order = ExitOrder(
            id=id,
            from_entry=from_entry,
            position_side=position_side,
            entry_price=entry_price,
            position_qty=position_qty,
            qty=qty,
            qty_percent=qty_percent,
            profit=profit,
            limit=limit,
            loss=loss,
            stop=stop,
            trail_price=trail_price,
            trail_points=trail_points,
            trail_offset=trail_offset,
            oca_name=oca_name,
            comment=comment,
            comment_profit=comment_profit,
            comment_loss=comment_loss,
            comment_trailing=comment_trailing,
            alert_message=alert_message,
            alert_profit=alert_profit,
            alert_loss=alert_loss,
            alert_trailing=alert_trailing,
            tick_size=self.tick_size,
            status=OrderStatus.ACTIVE,
        )

        # Handle trail_points=0 case (immediate activation)
        if trail_points is not None and trail_points == 0:
            order._activate_trailing(entry_price)

        # Store the order
        self.orders[id] = order

        # Add to OCA group if specified
        if oca_name is not None:
            if oca_name not in self.oca_groups:
                self.oca_groups[oca_name] = []
            self.oca_groups[oca_name].append(id)

        return order

    def cancel_order(self, order_id: str) -> bool:
        """
        Cancel an exit order.

        Args:
            order_id: ID of the order to cancel

        Returns:
            True if order was found and cancelled
        """
        if order_id in self.orders:
            order = self.orders[order_id]
            order.status = OrderStatus.CANCELLED
            del self.orders[order_id]

            # Remove from OCA group
            if order.oca_name and order.oca_name in self.oca_groups:
                if order_id in self.oca_groups[order.oca_name]:
                    self.oca_groups[order.oca_name].remove(order_id)

            return True
        return False

    def _cancel_oca_group(self, oca_name: str, except_order_id: str) -> None:
        """
        Cancel all orders in an OCA group except the specified one.

        Args:
            oca_name: Name of the OCA group
            except_order_id: Order ID to keep
        """
        if oca_name not in self.oca_groups:
            return

        orders_to_cancel = [
            oid for oid in self.oca_groups[oca_name]
            if oid != except_order_id
        ]

        for order_id in orders_to_cancel:
            self.cancel_order(order_id)

    def _check_order_fill(
        self,
        order: ExitOrder,
        price: float,
        is_limit_check: bool = True,
    ) -> Optional[ExitResult]:
        """
        Check if an order should be filled at the given price.

        Args:
            order: The exit order to check
            price: Current price
            is_limit_check: True if checking limit orders, False for stop orders

        Returns:
            ExitResult if filled, None otherwise
        """
        # Check limit order (take profit)
        limit_price = order.get_limit_price()
        if limit_price is not None:
            if order.position_side == PositionSide.LONG:
                if price >= limit_price:
                    return self._fill_order(order, limit_price, ExitType.PROFIT)
            else:
                if price <= limit_price:
                    return self._fill_order(order, limit_price, ExitType.PROFIT)

        # Check stop order (stop loss)
        stop_price = order.get_stop_price()
        if stop_price is not None:
            if order.position_side == PositionSide.LONG:
                if price <= stop_price:
                    return self._fill_order(order, stop_price, ExitType.LOSS)
            else:
                if price >= stop_price:
                    return self._fill_order(order, stop_price, ExitType.LOSS)

        # Update and check trailing stop
        order.update_trailing_stop(price)
        if order.check_trailing_stop_hit(price):
            return self._fill_order(
                order,
                order.trailing_stop_price,
                ExitType.TRAILING
            )

        return None

    def _fill_order(
        self,
        order: ExitOrder,
        fill_price: float,
        exit_type: ExitType
    ) -> ExitResult:
        """
        Fill an order and update its state.

        Args:
            order: The order to fill
            fill_price: Price at which order is filled
            exit_type: Type of exit (profit, loss, trailing)

        Returns:
            ExitResult with fill details
        """
        order.status = OrderStatus.FILLED
        order.fill_price = fill_price
        order.exit_type = exit_type

        qty = order.get_exit_qty()

        result = ExitResult(
            filled=True,
            exit_type=exit_type,
            fill_price=fill_price,
            qty=qty,
            comment=order.get_comment(),
            alert_message=order.get_alert_message(),
            order_id=order.id,
            from_entry=order.from_entry,
        )

        # Handle OCA group
        if order.oca_name:
            self._cancel_oca_group(order.oca_name, order.id)

        # Remove filled order
        if order.id in self.orders:
            del self.orders[order.id]

        return result

    def process_bar(self, bar: BarData) -> List[ExitResult]:
        """
        Process a bar and check all exit orders.

        Uses TradingView's intrabar price simulation:
        - If high closer to open: O → H → L → C
        - If low closer to open: O → L → H → C

        Args:
            bar: OHLCV bar data

        Returns:
            List of ExitResults for filled orders
        """
        results: List[ExitResult] = []

        if not self.orders:
            return results

        # Get intrabar price path
        price_path = bar.get_intrabar_path()

        # Process each price point in order
        for price in price_path:
            # Check each active order
            orders_to_check = list(self.orders.values())
            for order in orders_to_check:
                if order.status != OrderStatus.ACTIVE:
                    continue

                result = self._check_order_fill(order, price)
                if result:
                    results.append(result)

                    # If calc_on_order_fills, we might need special handling
                    if self.calc_on_order_fills:
                        # In TradingView, this triggers additional script execution
                        pass

        return results

    def process_tick(self, price: float) -> List[ExitResult]:
        """
        Process a single tick/price update.

        Used for live trading or tick-by-tick backtesting.

        Args:
            price: Current price

        Returns:
            List of ExitResults for filled orders
        """
        results: List[ExitResult] = []

        orders_to_check = list(self.orders.values())
        for order in orders_to_check:
            if order.status != OrderStatus.ACTIVE:
                continue

            result = self._check_order_fill(order, price)
            if result:
                results.append(result)

        return results

    def get_order(self, order_id: str) -> Optional[ExitOrder]:
        """Get an order by ID."""
        return self.orders.get(order_id)

    def get_active_orders(self) -> List[ExitOrder]:
        """Get all active orders."""
        return [o for o in self.orders.values() if o.status == OrderStatus.ACTIVE]

    def clear_all_orders(self) -> None:
        """Clear all orders."""
        self.orders.clear()
        self.oca_groups.clear()


# Utility functions for tick/price conversions

def price_to_ticks(price_diff: float, tick_size: float) -> float:
    """
    Convert price difference to ticks.

    Args:
        price_diff: Price difference
        tick_size: Minimum price increment

    Returns:
        Number of ticks
    """
    return price_diff / tick_size


def ticks_to_price(ticks: float, tick_size: float) -> float:
    """
    Convert ticks to price difference.

    Args:
        ticks: Number of ticks
        tick_size: Minimum price increment

    Returns:
        Price difference
    """
    return ticks * tick_size


def percent_to_ticks(
    percent: float,
    base_price: float,
    tick_size: float
) -> float:
    """
    Convert percentage to ticks.

    Useful for converting percentage-based stops/profits to tick values.

    Args:
        percent: Percentage (e.g., 2.5 for 2.5%)
        base_price: Base price for calculation
        tick_size: Minimum price increment

    Returns:
        Number of ticks
    """
    price_diff = base_price * (percent / 100.0)
    return price_to_ticks(price_diff, tick_size)
